# Generated by Django 4.2.11 on 2024-04-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_imgs/')),
                ('publish_date', models.DateField()),
                ('update_date', models.DateField()),
                ('status', models.CharField(choices=[('DFT', 'Draft'), ('RDY', 'Ready'), ('PUB', 'Published'), ('UPUB', 'Unpublished')], default='DFT', max_length=5)),
                ('views', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.user')),
            ],
        ),
    ]
