# Generated by Django 4.2.11 on 2024-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.TextField(default='', max_length=280),
        ),
    ]
