# Generated by Django 4.2.11 on 2024-05-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='albevallefo@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='about',
            field=models.TextField(blank=True, default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article', to='blog.user'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
